accept = [200, 403, 999]

exclude = [
  '%7B.*%7D',
  '\{.*\}',

  'http://127.0.0.1:8000',
  'http://localhost',

  '^/resume$'
]

remap = ["^/home/runner/work/arteii.net/arteii.net/ /home/runner/work/arteii.net/arteii.net/static/"]
